apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-authentication
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "11"
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: manifests/cluster-config/oauth/base
    repoURL: https://github.com/pumphouse-p/openshift-cluster-config.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true