apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

bases:
  - ../../../manifests/argocd/apps/oauth/base
  - ../../../manifests/argocd/apps/roles-and-bindings/base