apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
  - git:
      repoURL: https://github.com/pumphouse-p/openshift-cluster-config.git
      revision: applicationsets
      files:
      - path: "manifests/cluster-config/*"
  template:
    metadata:
      name: '{{path.basename}}-{{cluster}}'
    spec:
      project: cluster-config
      source:
        repoURL: https://github.com/pumphouse-p/openshift-cluster-config.git
        targetRevision: applicationsets
        path: '{{path}}'
      destination:
        server: '{{url}}'
        namespace: openshift-gitops