apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-cluster-autoscaler
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "11"
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: manifests/cluster-config/cluster-autoscaler/base
    repoURL: https://github.com/pumphouse-p/openshift-cluster-config.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false